<?xml version="1.0" encoding="utf-8"?><Database Name="Purrsoft" Class="ORMDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=(LocalDB)\LocalServer;Initial Catalog=Purrsoft;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="PurrsoftConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Ciudades" Member="Ciudades">
    <Type Name="Ciudades">
      <Column Name="ID_ciudad" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Nombre_ciudad" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
      <Association Name="Ciudades_Usuarios" Member="Usuarios" ThisKey="ID_ciudad" OtherKey="ID_ciudad" Type="Usuarios" />
    </Type>
  </Table>
  <Table Name="dbo.Detalle_historia" Member="Detalle_historia">
    <Type Name="Detalle_historia">
      <Column Name="ID_detalle_historia" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ID_mascota" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Nombre_doctor" Type="System.String" DbType="VarChar(60) NOT NULL" CanBeNull="false" />
      <Column Name="Motivo_consulta" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Descripcion_caso" Type="System.String" DbType="Text NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="Antecedentes" Type="System.String" DbType="Text NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="Valoracion_resultado" Type="System.String" DbType="Text NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="Prescripcion_medica" Type="System.String" DbType="Text NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="Fecha_consulta_medica" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Fecha_proxima_consulta" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="Mascotas_Detalle_historia" Member="Mascotas" ThisKey="ID_mascota" OtherKey="ID_mascota" Type="Mascotas" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Estados" Member="Estados">
    <Type Name="Estados">
      <Column Name="ID_estado" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Descripcion" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Association Name="Estados_Mascotas" Member="Mascotas" ThisKey="ID_estado" OtherKey="ID_estado_mascota" Type="Mascotas" />
    </Type>
  </Table>
  <Table Name="dbo.Mascotas" Member="Mascotas">
    <Type Name="Mascotas">
      <Column Name="ID_mascota" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Cedula_usuario" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Tipo_documento_usuario" Type="System.String" DbType="VarChar(3) NOT NULL" CanBeNull="false" />
      <Column Name="Nombre" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="Especie" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="Raza" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="Color" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="Sexo" Type="System.String" DbType="VarChar(2) NOT NULL" CanBeNull="false" />
      <Column Name="Fecha_nacimiento" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Señas_particulares" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ID_estado_mascota" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Mascotas_Detalle_historia" Member="Detalle_historia" ThisKey="ID_mascota" OtherKey="ID_mascota" Type="Detalle_historia" />
      <Association Name="Estados_Mascotas" Member="Estados" ThisKey="ID_estado_mascota" OtherKey="ID_estado" Type="Estados" IsForeignKey="true" />
      <Association Name="Usuarios_Mascotas" Member="Usuarios" ThisKey="Cedula_usuario,Tipo_documento_usuario" OtherKey="Numero_doc,Tipo_documento" Type="Usuarios" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Permisos" Member="Permisos">
    <Type Name="Permisos">
      <Column Name="ID_permiso" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Descripcion" Type="System.String" DbType="VarChar(15) NOT NULL" CanBeNull="false" />
      <Association Name="Permisos_Roles_Permiso" Member="Roles_Permiso" ThisKey="ID_permiso" OtherKey="ID_permiso" Type="Roles_Permiso" />
    </Type>
  </Table>
  <Table Name="dbo.Roles" Member="Roles">
    <Type Name="Roles">
      <Column Name="ID_rol" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Descripcion" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
      <Association Name="Roles_Roles_Permiso" Member="Roles_Permiso" ThisKey="ID_rol" OtherKey="ID_rol" Type="Roles_Permiso" />
      <Association Name="Roles_Usuarios" Member="Usuarios" ThisKey="ID_rol" OtherKey="ID_rol" Type="Usuarios" />
    </Type>
  </Table>
  <Table Name="dbo.Roles_Permiso" Member="Roles_Permiso">
    <Type Name="Roles_Permiso">
      <Column Name="ID_rol" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ID_permiso" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="Permisos_Roles_Permiso" Member="Permisos" ThisKey="ID_permiso" OtherKey="ID_permiso" Type="Permisos" IsForeignKey="true" />
      <Association Name="Roles_Roles_Permiso" Member="Roles" ThisKey="ID_rol" OtherKey="ID_rol" Type="Roles" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Usuarios" Member="Usuarios">
    <Type Name="Usuarios">
      <Column Name="Numero_doc" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Tipo_documento" Type="System.String" DbType="VarChar(3) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ID_rol" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Nombres" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="Apellidos" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="Telefono" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Direccion" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Email" Type="System.String" DbType="VarChar(40) NOT NULL" CanBeNull="false" />
      <Column Name="ID_ciudad" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Password_u" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="Imagen" Type="System.String" DbType="VarChar(70)" CanBeNull="true" />
      <Association Name="Usuarios_Mascotas" Member="Mascotas" ThisKey="Numero_doc,Tipo_documento" OtherKey="Cedula_usuario,Tipo_documento_usuario" Type="Mascotas" />
      <Association Name="Ciudades_Usuarios" Member="Ciudades" ThisKey="ID_ciudad" OtherKey="ID_ciudad" Type="Ciudades" IsForeignKey="true" />
      <Association Name="Roles_Usuarios" Member="Roles" ThisKey="ID_rol" OtherKey="ID_rol" Type="Roles" IsForeignKey="true" />
    </Type>
  </Table>
</Database>